develop_config:
  login_mode: {config}{manuel}

host_config:
  host: {host}
  account: {account}
  password: {password}

crawler_config:
  cool_down_time: 30
  remove_prev_connect: false
  search_word: {searchWord}
